config/routes.rb
Rails.application.routes.draw do
  #resources :friends

  root 'home#index'
  get 'home/about'
  resources :friends do
    resources :blogs
  end

  get 'error', to: 'blogs#error', as: 'error'
  get  'friend/:friend_id/blog/:id/publish', to: 'blogs#publish', as: 'blog_publish'
  get 'friend/new', to: 'friends#new', as: 'newforms_friends'


  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :friend
end

app/models/friend.rb
class Friend < ApplicationRecord
  has_many :blogs, dependent: :destroy
  accepts_nested_attributes_for :blogs,  reject_if: :all_blank, allow_destroy: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


  def index
    @friend = Friend.find params[:friend_id]
    @blogs = @friend.blogs.sort_by &:id

  end

  def new
    @friend = Friend.find params[:friend_id]
    @blog = Blog.new
  end

  def create
    user = Friend.find params[:friend_id]
    bg_params = params.require(:blog)
    blog = user.blogs.create(title: bg_params[:title], content: bg_params[:content], status: 0)

    if blog.save
      redirect_to friend_blogs_path, notice: "Blog create Successfully.."
    else
      render :new, notice: "Oh No.."
    end
  end

  def edit
    @friend = Friend.find params[:friend_id]
    @blog = Blog.find params[:id]

    user_id = params[:friend_id]
    blog_id = Blog.find params[:id]
    if Friend.exists? id: user_id
      @friend = Friend.find user_id
      if Blog.exists? id: blog_id, friend_id: user_id
        @blog = Blog.find params[:id]
      else
        redirect_to error_path, alert: "No blog found of the user: #{user_id} with the blog id: #{blog_id}"
      end
    else
      redirect_to error_path, alert: "No user found with the user id #{user_id}"
    end


  end


  def update
    user = user_exist params[:friend_id]
    blog = user.blogs.find params[:id]
    @blog = Blog.find params[:id]
    if @blog.update(blog_param)
      redirect_to friend_blogs_path(user, blog), notice: "Updated Successfully"
    else
      redirect_to edit_friend_blog_path(params[:friend_id], blog_id), notice: "Failed to Update"
    end
  end



  def show

    @blog = Blog.find params[:id]

  end

  def destroy

    @blog = Blog.find params[:id]
      if @blog
        @blog.destroy
        redirect_to friend_blogs_path, notice: "Blog Deleted successfully..."
      else
        redirect_to friend_blogs_path, notice: "Blog is not found to delete"
      end
  end

  def publish
    user = user_exist params[:friend_id]
    blog = user.blogs.find params[:id]

    if blog.update(status: 1)
      redirect_to friend_blogs_path(user, blog), alert: 'User/Blog id error'
      end

  end

  private

  def user_exist(friend_id)
    if Friend.exists? friend_id
      return Friend.find friend_id
    else
      redirect_to error_path, alert: "No user exits with user id: #{friend_id}"
    end
  end

  def blog_param
    params.require(:blog).permit( :title, :content, :status)
  end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all

  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new

  end

  # GET /friends/1/edit
  def edit

  end

  # POST /friends or /friends.json

  def create
    @friend = Friend.new(friend_params)
    #raise friend_params.inspect
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "User Add Successfully.." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  #my create method


  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)

        #raise friend_params.inspect
        format.html { redirect_to friend_url(@friend),  notice: "User Details Update Successfully.."}
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    user = Friend.find params[:id]

    user.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "User Delete Successfully.."}
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :twitter, blogs_attributes: [:friend_id, :id, :title, :content, :_destroy])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/_form.html.erb
<%= form_with model: [ @friend, @blog ]  do |form| %>
  <div class="form-group">
    <%= form.label :title, style: "display: block"%><br>
    <%= form.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= form.label :Blog, style: "display: block"%><br>
    <%= form.text_area :content, class:"form-control"%>
  </div>

</br>
    <%= form.submit class: 'btn btn-primary' %>



<% end %>

app/views/blogs/edit.html.erb
<h2>Update this blogs </h2>


<%= render "blogs/form" %>
</br>
<%= button_to "delete",friend_blog_path(), :method => :delete, class:"btn btn-danger"%>

<% if @blog.status == 0 || @blog.status == nil%>
  <%= link_to 'Publish the Blog', blog_publish_path, class: 'd-block btn btn-secondary' %>
<% end %>

app/views/blogs/error.html.erb
<h2>
  <% if flash[:alert] %>
    <%= flash[:alert]%>
  <% end %>
</h2>

app/views/blogs/index.html.erb
<table class = "table table-striped table-bordered table-hover">
  <thead class="table-dark">
  <tr>
    <th>Blog No</th>
    <th>Blog Title</th>
    <th>Status</th>
    <th>Edit</th>

  </tr>
  </thead>

  <tbody>
  <% @friend.blogs.each do |blog| %>
    <tr>
      <td><%= blog.id %></td>
      <td><p><%=blog.title %> | <%= link_to "Show Blog", friend_blog_path(@friend,blog)%></p>
      </td>

      <td>
        <%if blog.status == 0 || blog.status ==nil %>

          <p>Draft</p>
        <%else%>
        <p>Publish</p>
          <%end %>

      </td>
      <td><p><%= link_to "Edit This",  edit_friend_blog_path(@friend,blog) %></p></td>


    </tr>
  <% end %>
  </tbody>

</table>

<%= link_to 'Add new Blog', new_friend_blog_path, class: "btn btn-secondary" %>

app/views/blogs/new.html.erb
<h2>Create new Blog</h2>
<%= render 'blogs/form'%>

app/views/blogs/show.html.erb
<div class="mt-4 p-5 bg-light text-black rounded">
  <h1 class="display-4" style="color:cadetblue;">
    <%= @blog.title %>
  </h1>
  <p class="lead"><%= @blog.content %>
  </p>
  <hr class="my-4">

  </br>
  <%= link_to "Back", friend_blogs_path, class:"btn btn-primary"%>
  <br/>
  <br/>
</div>

app/views/friends/_blog_fields.html.erb
<div class="nested-fields">

  <div class="field">
    <%= f.label :Blog_Title%><br>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Blog_Content%><br>
    <%= f.text_area :content, class:"form-control"%>
  </div>
    <%= link_to_remove_association "Remove Blog", f, class: 'btn btn-danger my-2' %>

</div>

app/views/friends/_form.html.erb
<%= form_for @friend do |form| %>


  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name%>
    <%= form.text_field :last_name, class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :email%>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter%>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <h3>Blogs</h3>
    <%= form.fields_for :blogs do |blog| %>
      <%= render 'blog_fields', f: blog %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Blog', form, :blogs, class: 'btn btn-primary my-2' %>
    </div>


  <div class="actions">
     <%= form.submit 'Save', class: "btn btn-success my-2"%>
  </div>
 


<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing User</h1>

<%= render "form", friend: @friend %>

<br>

<div>

  <%= link_to "Show this User", @friend, class: 'btn btn-secondary'%> |
  <%= link_to "Back to Users", friends_path, class: 'btn btn-primary' %>
</div>

app/views/friends/index.html.erb
<table class = "table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Twitter</th>
      <th>Info</th>
      <th>Blogs</th>

    </tr>
  </thead>

  <tbody>
  <% @friends.each do |friend| %>
    <tr>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= friend.email %></td>
      <td><%= friend.twitter %></td>

      <td><%= link_to "Show User info", friend, class: "btn btn-outline-info" %></td>
      <td><%= link_to "Show User Blogs",  friend_blogs_path(friend), class: "btn btn-outline-info"%></td>

 </tr>
  <% end %>
  </tbody>

</table>
</br>

<%= link_to 'Add new users With blog', new_friend_path, class: "btn btn-outline-success" %>

app/views/friends/new.html.erb
<h1>Add New User</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to Users", friends_path, class:'btn btn-primary' %>
</div>

app/views/friends/show.html.erb
<div class="mt-4 p-5 bg-light text-black rounded">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead"><%= @friend.email %> | <%= @friend.twitter%>
  </p>
  <hr class="my-4">

  </br>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary"%>  |
  <%= link_to "Back", friends_path, class:"btn btn-primary"%>
  <br/>
  <br/>

  <%= button_to "Delete", @friend, method: :delete, data: {confirm:"Are you sure?"}, class:"btn btn-danger"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Blog App',root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", home_about_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Users", friends_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add User", new_friend_path,class:"nav-link" %>
        </li>

      </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us...</h1>

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

  <title>Jumbotron Template for Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="jumbotron.css" rel="stylesheet">
</head>

<body>



<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">This Is a User Blog app</h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Everything </h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Is</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Fun</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; Company 2022</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>

app/views/layouts/application.html.erb
<%= javascript_include_tag "application" %>

<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Friends App</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>


</head>
<body>
  <!--call partial page -->
  <%= render 'home/header' %>

  <div class="container">
    <% if notice %>
    <%= render 'layouts/alerts' %>
    <% end %>

  </br>
    <%= yield %>
  </div>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>